<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>SimpleMessageBroker.Client</PackageId>
    <Description>C# Client SDK for SimpleMessageBroker — a lightweight single-node message queue middleware.</Description>
    <Authors>MinGo</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/FFFirer/MinGo.SimpleMessageBroker</RepositoryUrl>
    <PackageTags>message-queue;message-broker;sdk;messaging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
  </ItemGroup>

</Project>
